#!/bin/bash

echo "Installing MCN SDK"
curl -k -o $BUNDLE_DIR/sdk.tar.gz 'https://owncloud.mobile-cloud-networking.eu/owncloud/public.php?service=files&t=01ad0519e7e4ad9bc8fdbf5f959f183e&download'
pip install $BUNDLE_DIR/sdk.tar.gz
pip install python-heatclient six python-novaclient python-ceilometerclient python-neutronclient bottle sqlalchemy==0.9.8 httplib2
echo "Installing MCN SM SO lib"
curl -k -o $BUNDLE_DIR/sm.tar.gz 'https://owncloud.mobile-cloud-networking.eu/owncloud/public.php?service=files&t=3ec7178ae3587866a0d94e27af95024b&download'
pip install $BUNDLE_DIR/sm.tar.gz